### ISSUE TITLE
Should use score API, not scrape the pub.dev UI

### ISSUE THREAD

**Issue by mit-mit** [bruno-garcia/badges.bar#2]
Hi @bruno-garcia, thanks for creating this tool, very useful!

It looks like the implementation depends on scraping the pub.dev web UI:
https://github.com/bruno-garcia/badges.bar/blob/main/lib/src/pub_client.dart#L17

That is likely going to lead to instability as we may change details of the UI in the future. It would be better to use an API, e.g.: 

https://pub.dev/api/packages/http/score
```
{"grantedPoints":110,"maxPoints":110,"lastUpdated":"2020-09-04T07:11:51.274501Z"}
```

**Comment by mit-mit** [comment]
Note, however, that we unfortunately don't have all three score components in the API, so this would be blocked on us resolving https://github.com/dart-lang/pub-dev/issues/3996 first.

**Comment by bruno-garcia** [comment]
@mit-mit thanks a lot for raising this. I noticed the site was rendered with the data embedded and wasn't aware of an endpoint to fetch the 3 (or any) score.

I'd be glad to change the code to hit an endpoint that returns a JSON as opposed to parsing the html which not only performs badly, it'll surely break, eventually.

Also thanks for raising the issue on pub.dev. I'm following it and once that's addressed, I'll fix loading the badges from the API.

**Comment by bruno-garcia** [comment]
It's live:

![image](https://user-images.githubusercontent.com/1633368/93032960-318e5380-f602-11ea-8f2c-1a39b164988c.png)
