### ISSUE TITLE
consider tweaking the size and padding to bring these badges in-line with badges from other services

### ISSUE THREAD

**Issue by devoncarew** [bruno-garcia/badges.bar#26]
As far as I can tell, there's a pseudo-standard for the look of badges here:

https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md#aesthetics

It includes things like the left, right, top, and bottom padding and the general height and width. From a quick look at badges here, it looks like the dart icon needs to be made a bit smaller, and the left and right padding around some of the text could be reduced.

I see the implementation for the svg generation is here: https://github.com/bruno-garcia/badges.bar/blob/main/lib/src/svg.dart. Some aspects of the layout look straightforward enough to tweak; I'm not sure how to implement other things however - things that would require measuring the width of text.

**Comment by bruno-garcia** [comment]
Thanks for sharing and sorry for the late reply. I agree padding seems off depending on the size of the text.
That said, ideally, shields.io gets support for these badges having the same look (Dart logo on the left), and I can sunset this service.

I raised an issue: https://github.com/badges/shields/issues/8086

**Comment by bruno-garcia** [comment]
See #27
