### ISSUE TITLE
Points and popularity is mixed up

### ISSUE THREAD

**Issue by mit-mit** [bruno-garcia/badges.bar#6]
Looks like the numbers for points and popularity are mixed up:

<img width="771" alt="Screenshot 2020-09-17 at 10 25 47" src="https://user-images.githubusercontent.com/13644170/93442166-3d169e80-f8d0-11ea-8e4b-ff5e12c27880.png">

<img width="816" alt="Screenshot 2020-09-17 at 10 26 28" src="https://user-images.githubusercontent.com/13644170/93442272-43a51600-f8d0-11ea-8c35-a671c71266b7.png">

**Comment by bruno-garcia** [comment]
Thanks again for fixing this (embarrassing) bug :)

I've publish a new version (v0.1.1) to pub.dev and also rolled out live.
For packages loaded in the last hour will be returning the cached (wrong) badges.

I tested with this package to confirm the right values:
http://badges.bar/flutter_bloc/popularity
http://badges.bar/flutter_bloc/pub%20points

**Comment by mit-mit** [comment]
No worries, yes looks good now!
